# app/config.py
import os

OPENROUTER_API_KEY = "OPENROUTER_API_KEY"


OPENROUTER_URL = "OPENROUTER_URL"
OPENROUTER_MODEL = "MODEL_NAME"

QDRANT_URL = "CLOUD OR LOCAL URL"

EMBEDDING_MODEL = "sentence-transformers/all-MiniLM-L6-v2"
